### ISSUE TITLE
Implement inter-service communication in Quarkus microservice

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/my-thai-star#1026]
Booking management microservice has a requirement to communicate with order management and user management.

**Comment by sujith-mn** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/my-thai-star/1026?planning-poker) with ZenHub @ssarmokadam @suprishi

**Comment by isandesh1986** [comment]
Not relevant after latest DA meeting. Hence, removed from core team backlog.
