### ISSUE TITLE
Database toggle #70 not working

### ISSUE THREAD

**Issue by AbhayChandel** [devonfw/my-thai-star#103]
Category: Bug or enhancement

Severity: Low , Medium, High, Critical

Expected behaviour (In case of bug)

Actual/current behaviour (In case of bug)

Steps to reproduce (In case of bug)

Description of issue / expected enhacement /Comments

Your environment - windows/Linux, Devonfw version , component

**Comment by hohwille** [comment]
Any more details? We can not reproduce or analyse this issue without further details.
Please always include stacktrace, screenshot or similar in bug issues.

**Comment by AbhayChandel** [comment]
This is an older issue and should be rejected and closed.
