### ISSUE TITLE
Incomplete authorization in MTSJ

### ISSUE THREAD

**Issue by hohwille** [devonfw/my-thai-star#113]
Category: enhancement (flaw)

Severity: Medium

Expected behaviour: more fine grained authorization to demonstrate the feature
https://github.com/oasp/my-thai-star/blob/develop/java/mtsj/core/src/main/resources/config/app/security/access-control-schema.xml

Actual/current behaviour: permission for every use-case. When working on this please already consider https://github.com/oasp/oasp4j/pull/631

Description of issue / expected enhacement /Comments:
According to documentation (https://github.com/oasp-forge/oasp4j-wiki/wiki/guide-access-control#access-control-config) every logic/use-case method should have an authorization.
However in MTSJ no such method has an authorization:
https://github.com/oasp/my-thai-star/blob/develop/java/mtsj/core/src/main/java/io/oasp/application/mtsj/dishmanagement/logic/impl/DishmanagementImpl.java#L72
The funny thing is that we even enforced this with a JUnit in app template that fails if authorization is missing. This JUnit is present in MTSJ:
https://github.com/oasp/my-thai-star/blob/develop/java/mtsj/core/src/test/java/io/oasp/application/mtsj/general/common/PermissionCheckTest.java#L31
However, as MTSJ is not following the use-case approach there is not a single use-case and therefore this JUnit finds an empty list of use-cases and therefore does nothing.

IMHO it is important to demonstrate the core features of OASP4J in our sample app and especially give a good and high quality showcase for security aspects. Therefore I would suggest to change/fix this soon.

**Comment by hohwille** [comment]
Please also see here:
https://github.com/devonfw/devon4j/wiki/guide-access-control#access-control-config

The `access-control-schema.xml` is old and deprecated. MTS should follow the latest devonfw guide.

**Comment by fskalny** [comment]
The last 2 links from the original post updated from oasp to devonfw:

https://github.com/devonfw/my-thai-star/blob/develop/java/mtsj/core/src/main/java/com/devonfw/application/mtsj/dishmanagement/logic/impl/DishmanagementImpl.java#L72

https://github.com/devonfw/my-thai-star/blob/develop/java/mtsj/core/src/test/java/com/devonfw/application/mtsj/general/common/PermissionCheckTest.java#L31
