### ISSUE TITLE
Incomplete/missing I18N in MTSJ

### ISSUE THREAD

**Issue by hohwille** [devonfw/my-thai-star#114]
Category: enhancement

Severity: Low

Expected behaviour: Exception messages should be internationalized and have ability to be localized.

Actual/current behaviour: Exception message texts are encoded as strings and no way is demonstrated how to localize them (would be possible but the current way is more of an anti-pattern).

Steps to reproduce: change your locale - you will always get the same error text.

Description of issue / expected enhacement /Comments:
Here is a link to the code:
https://github.com/oasp/my-thai-star/blob/99e16c8da132a0f6ca9c8714b39685b260b7b783/java/mtsj/core/src/main/java/io/oasp/application/mtsj/bookingmanagement/common/api/exception/CancelInviteNotAllowedException.java#L12
First hit, seems to apply to every exception message - here another example:
https://github.com/oasp/my-thai-star/blob/99e16c8da132a0f6ca9c8714b39685b260b7b783/java/mtsj/core/src/main/java/io/oasp/application/mtsj/ordermanagement/common/api/exception/NoInviteException.java#L15

As our sample (MTS) is a showcase that shall demonstrate our core features, I would expect it to use i18n properly by defining a NlsBundle. 
Ideally we also provide localized properties for Spanish and German (if other countries like France or Netherlands want to contribute, they are most welcome). The localization (for multiple languages other then English) is of course nice to have and shall not block this issue. It can also happen later as contributors are available.

**Comment by hohwille** [comment]
See 
* http://m-m-m.sourceforge.net/apidocs/net/sf/mmm/util/nls/api/package-summary.html#documentation
* https://github.com/hohwille/devon4j/blob/feature/79-documentation/documentation/guide-i18n.asciidoc

**Comment by tliszyns** [comment]
I intend to resolve this issue. Get in touch in case you already work on it.
