### ISSUE TITLE
Upgrade to oasp4j 3.0.0

### ISSUE THREAD

**Issue by hohwille** [devonfw/my-thai-star#125]
oasp4j version 3.0.0 is already on its way. MTSJ shall be upgraded. The process should look like this:
* [x] have a ioasp4j release 3.0.0-alpha.1 in maven central
* [x] upgrade MTSJ to that version
* [x] if MTSJ has trouble create according issues in OASP4J and get them solved
* [x] have a ioasp4j release 3.0.0 in maven central
* [x] finally upgrade MTSJ to that version

See also https://github.com/oasp/oasp4j/issues/639

**Comment by sjimenez77** [comment]
Should we close this issue as the devon4j migration is already done?

**Comment by hohwille** [comment]
IMHO done.
