### ISSUE TITLE
MTSJ should only use spring-data based on devon4j-jpa-spring-data

### ISSUE THREAD

**Issue by vapadwal** [devonfw/my-thai-star#127]
Category: enhancement

Severity: High

Description : MTSJ is currently using JPA based on oasp4j 2.4.0, as per the oasp4j release 3.0.0 it should be updated to spring-data

Also MTSJ should Update to spring boot 2

Your environment - windows/Linux, Devonfw version , component

**Comment by sjimenez77** [comment]
Solved with PR #135
