### ISSUE TITLE
Display app version

### ISSUE THREAD

**Issue by amarinso** [devonfw/my-thai-star#133]
Category: enhancement
Severity: Low

I would like to have a fixed/default/known route on the application that displays the name and version deployed.

This is useful to determine both the health of the application and the correct deployment of a new version.

Maybe the solution is that a new static HTML/JSON file is generated during application build with this content on a known file name.

**Comment by amarinso** [comment]
Maybe this is useful
https://medium.com/@amcdnl/version-stamping-your-app-with-the-angular-cli-d563284bb94d

**Comment by hohwille** [comment]
We had done such things before in customer projects by "injecting" these infos into variables of the `index.html`. With maven filtering this was super easy. However, nowadays we want to have the client build to work isolated from Java tooling so IMHO scripts for package.json would be better.

**Comment by amarinso** [comment]
@sjimenez77 talked me today about schematics, maybe that would be the way
