### ISSUE TITLE
Pagination issues while migration to devon4j

### ISSUE THREAD

**Issue by vapadwal** [devonfw/my-thai-star#142]
Below are the issues detect while migration to devon4j

- First the filters pagination doesn't refresh to the first page.
- When try to filter on waiter orders or reservations tabs by attribute that doesn't exist, it doesn't refresh the data table, it should show the next text: No results to display. It worked in the past and showed the text in the language selected.
- When try to filter on Menu by attribute that doesn't exist, the web is showing every time the green bar as if we need to wait until the components are load. It worked in the past and when the search returned blank list the green bar stopped and the web didn't show nothing.

**Comment by sjimenez77** [comment]
Solved in PR #143
