### ISSUE TITLE
CI/CD instructions should include a detailed list of required plugins/tools and their versions

### ISSUE THREAD

**Issue by maweck** [devonfw/my-thai-star#149]
Category: enhancement

Severity: High

Description of issue / expected enhancement /Comments

To create a "PL Template", we need to know which:
- Jenkins Plugins
- Custom Tools (e.g. Yarn, ..)
Are used and which version is compatible with the latest release of my-thai-star.

**Comment by sjimenez77** [comment]
Closing issue as it is already addressed in #153.
