### ISSUE TITLE
CI/CD Jobs should be splitted into a "build" and "deploy" part

### ISSUE THREAD

**Issue by maweck** [devonfw/my-thai-star#150]
Category: enhancement

Severity: High

Description of issue / expected enhacement /Comments

Right now the my-thai-star repo contains a CI/CD Jenkinsfile for the Angular and Java part which do both actions: Build and deploy. Each Jenkinsfile should be splitted into two different Jenkinsfiles, one that builds the application and pushes it to Nexus and a second one that deploys the application to a VM.

**Comment by dario-rodriguez** [comment]
One more thing, I couldn't test the deploy pipeline. I will continue with that the next week but I want to deliver at least one version in order to don't block you anymore.

Kind regards.

**Comment by maweck** [comment]
Thank you very much @dario-rodriguez  - We also need some more days to be able to test this, so don't worry :) - I'll provide some feedback here as soon as I can.
