### ISSUE TITLE
MTSJ should satisfy devonfw architecture

### ISSUE THREAD

**Issue by hohwille** [devonfw/my-thai-star#152]
Category: enhancement

Severity: Medium

Expected behaviour:
MTS is the reference app for devonfw and acts as a blue print. It should therefore follow our own guidelines. For MTSJ this means:
* https://github.com/devonfw/devon4j/wiki/architecture#application-architecture
* https://github.com/devonfw/devon4j/wiki/coding-conventions#packages

Actual behaviour:
* Package-conventions are violated
* dependencies do not match technical architecture
* business components do have cyclic dependencies

Steps to reproduce:
Use e.g. https://github.com/devonfw/sonar-devon-plugin#sonar-devon-plugin to analyze the code.

Description of issue / expected enhacement /Comments
I will attach the sonarqube report.

Your environment:
Windows, but should not matter

**Comment by hohwille** [comment]
For some reason github does not support HTML attachments so I just zipped it.
[SonarQubeDevonReport.zip](https://github.com/devonfw/my-thai-star/files/2634530/SonarQubeDevonReport.zip)

**Comment by vapadwal** [comment]
I have put some of these issues in excel, and have solved some of them. please see the sheet
I could upload the new sonar report.

[Sonar_mtsj_issues.xlsx](https://github.com/devonfw/my-thai-star/files/2801706/Sonar_mtsj_issues.xlsx)

**Comment by hohwille** [comment]
> As this   was having {@link ImageEntity} , there was an import for ImageEntity. This   has been removed

Did you fix this by removing the import and fully qualifying the @link? This is the appropriate fix. Do not remove the @link itself as otherwise our JavaDoc looses quality.

**Comment by hohwille** [comment]
> Layer 'null' is invalid.

Your solutions on these issues seem all fully correct.

> Dataaccess layer shall [not] depend on logic layer

Jep, TOs like SeachCriteriaTo have to be in `common.api.to`. Perfect fix. Is that still wrong in CobiGen Templates? We have to ensure we also fix the root of the problem.
@maybeec are you aware of this issue?

**Comment by hohwille** [comment]
Actually this is also a good test of the sonar-devon-plugin rules and their description. Some of them seem to be clear and guide to the proper fix but others not. I will try to collect the learnings from here and ensure we improve the rules and their documentation accordingly. It would be awesome if we have enhanced documentation for each rule showing the BAD and the GOOD example for a given rule with rationale/explanation/motivation.

**Comment by jdiazgon** [comment]
> Jep, TOs like SeachCriteriaTo have to be in common.api.to. Perfect fix. Is that still wrong in CobiGen Templates?

Those [templates ](https://github.com/devonfw/tools-cobigen/tree/master/cobigen-templates/templates-devon4j/src/main/templates/crud_java_server_app/templates/java/%24%7Bvariables.rootPackage%7D/%24%7Bvariables.component%7D/logic/api/to)are generated to package `logic.api.to.`

> It would be awesome if we have enhanced documentation for each rule showing the BAD and the GOOD example for a given rule with rationale/explanation/motivation.

I agree, from my side I don't know why exactly now we need to move those templates to `common`

**Comment by maybeec** [comment]
@hohwille We are generating TOs to `logic.api.to`. This should be fine, right?
The interface is even generated to `common.api`, so I don't see the issue here.

**Comment by vapadwal** [comment]
> @hohwille I have few issue that need some inputs
> 
> Issue 1:
> mtsj-coresrc/.../ordermanagement/dataaccess/api/OrderEntity.java
> Access from component 'ordermanagement' to 'bookingmanagement' is not allowed. Only the following components are allowed dependencies: [dishmanagement, general, imagemanagement, mailservice]
> 
> How to handle this kind of error, OrderEntity and BookingEntity has One to many relationship, so
> 
> OrderEntity has a reference for BookingEntity
> 
> @manytoone(fetch = FetchType.EAGER)
> @JoinColumn(name = "idBooking")
> public BookingEntity getBooking() {
> 
> ```
> return this.booking;
> ```
> }
> 
> And BookingEntity has below.
> 
> @OneToMany(mappedBy = "booking", fetch = FetchType.EAGER)
> public List getOrders() {
> 
> ```
> return this.orders;
> ```
> }
> 
> Also a per sonar I cant put cyclic relationship between ordermanagement and bookingmanagement
> 
> Issue 2:
> mtsj-coresrc/.../ordermanagement/logic/impl/OrdermanagementImpl.java
> Access from component 'ordermanagement' to 'bookingmanagement' is not allowed. Only the following components are allowed dependencies: [dishmanagement, general, imagemanagement, mailservice]
> 
> Currently there are few usecase which need bookingmanagement, like delete of order, sending mail when order is confirm.
> 
> So both issues requires ordermangement and bookingmanagement relationship

Update : @trivesc  was able to solve issue 2, moved usecase (delete of order, sending mail ) to booking management
