### ISSUE TITLE
@angular/cli in devDependencies

### ISSUE THREAD

**Issue by amarinso** [devonfw/my-thai-star#154]
Category: Bug or question
Severity: Medium

Expected behaviour: 
no warning from executing `ng serve`

Actual/current behaviour:
```
Your global Angular CLI version (7.1.1) is greater than your local
version (7.0.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
```

Steps to reproduce:
I installed (2018-11-6) `npm install -g @angular/cli` and tried to serve the project `ng serve`
my-thai-star/develop branch

My question is why is it required the @angular/cli module on the package.json if it is installed globally.
Following instructions on our wiki gives this warning as the first experience you get from trying to get experience devon4ng to work... which is bad in my opinion

**Comment by sjimenez77** [comment]
You need a local `@angular/cli` in order not to mess up things with the global one. When you run an Angular CLI command inside a project you run **the local Angular CLI**, so you do not have to worry about  the version that you have globally. This is the version of the project that will be used by all the developers of the team independently of the global version that each one has installed.  

In any case, Angular CLI notifies you that you could have a different global version instead but only for information purposes.
