### ISSUE TITLE
Angular router tracing configuration on config

### ISSUE THREAD

**Issue by amarinso** [devonfw/my-thai-star#163]
Category: enhancement
Severity: Low

`enableTracing` is enabled on the `app-routing.module.ts` file so it shows when you open the console.

I propose that this setting is configured on the config file so people has a centralized point of configuring the application behavior.

i.e `enableRouterTracing` property

**Comment by anmaso** [comment]
Maybe it is better to have this on the environment files so it can be set to false on production and only enabled for debug

**Comment by suprishi** [comment]
PR https://github.com/devonfw/my-thai-star/pull/1004

**Comment by suprishi** [comment]
PR merged after approval from Santos. Closing this issue.
