### ISSUE TITLE
Angular - Docker - select better base image for builds

### ISSUE THREAD

**Issue by amarinso** [devonfw/my-thai-star#175]
Category: enhancement
Severity: High

Currently Docker image for Angular is building with `blairguk/node-sass-alpine:8.9.4 AS build` this is not acceptable as this is not a trusted source.

Either we provide the base image for building, or use another official node image for this step.

**Comment by markusschuh** [comment]
This issue can be closed.

This was already implemented, see e.g. [this commit](https://github.com/devonfw/my-thai-star/commit/bdd0763539e0ca7962d9a2f0c45482573126cedb#diff-b5b43b4800bdf05cb9ffa5e1c40edeed)  Also I can no longer detect [any use of this image](https://github.com/devonfw/my-thai-star/search?q=blairguk&unscoped_q=blairguk) inside my-thai-star.
