### ISSUE TITLE
Angular - i18n usage ergonomics

### ISSUE THREAD

**Issue by amarinso** [devonfw/my-thai-star#177]
I see that we use ngx-translate for i18n, that may give us nice options, but it messes the code too much.

Take a look at this fragment:

```
this.translateService.get('bookTable.dialog.bookingSuccess')
          .subscribe((text: string) => {
            this.snackBar.openSnack(text, 4000, 'green');
          });
```
This is required to use an internationalized text on a service... the boilerplate completely masks the purpose of the code.

I suppose that the reason is that the i18n values can potentially be resolved asynchronously so you have to make sure that the text is available before using it.

What can we do to simplify this usage? I can imagine:
- Delay application initialization until i18n assets are resolved
    - More or less the same is doing the config service when looking for external configuration values, we can imagine that since application is already being delayed, by the moment it gets the external config it also gets the i18n assets (unless the language is being configured externally )
- Introduce some TS decorators of utilities to simplify the usage

alternatives?

**Comment by amarinso** [comment]
It seems that i18n will be addressed soon in Angular + ivy so I imagine that we will switch back to "official Angular" when released

see this [https://github.com/ngx-translate/core/issues/495](https://github.com/ngx-translate/core/issues/495)

**Comment by anmaso** [comment]
It seems we are not coherent with ngx-translate usage neither. 

On user-area.service we are assuming the translation will be available at the time of usage by asking for it on the constructor.

**Comment by sjimenez77** [comment]
Hi @anmaso, the code you are pointing is completely fine. What we include in the constructor of the `user-area.service.ts` is the Translate service by Dependence Injection. 

The translations are available because are already initialized in the `app.module.ts` and you can request them lazily as an Observable that you can subscribe to get the translation you want.
