### ISSUE TITLE
Routing module best practice

### ISSUE THREAD

**Issue by tlueecke** [devonfw/my-thai-star#18]
For our routes we define the module as a constant instead of following the recommended way of Angular:

https://angular.io/guide/ngmodule#app-routing

From my point of view this would be the cleaner approach.

**Comment by dumbNickname** [comment]
There is one more thing to be added here - routes can be specified on per module basis:

``` typescript
export const bookDetailsRoute: Route = {
  path: 'book/:id',
  component: BookDetailsComponent,
  resolve: {
   book: BookDetailsResolver
  }
  };
    
  export const newBookRoute: Route = {
  path: 'book',
  component: BookDetailsComponent
  };


```
and then aggregated on route module level:

``` typescript

export const appRoutes: Routes = [

  {
  path: '', pathMatch: 'full', redirectTo: '/book-app/books'
  },
  {
  path: 'book-app',
  children: [
   bookOverviewRoute,
   bookDetailsRoute,
   newBookRoute
  ]
  }];

```
This pattern might be useful for bigger apps as well :smile:

**Comment by maybeec** [comment]
Protocol 26.07.

* Introduce angular pattern for routes including a dedicated routing module (https://angular.io/guide/ngmodule#app-routing) following the best practices

**Comment by sjimenez77** [comment]
PR #30 submitted

**Comment by sjimenez77** [comment]
Hi @tlueecke, @maybeec, 
this issue is possibly solved with this PR https://github.com/oasp/my-thai-star/pull/30. May we close this?

**Comment by hohwille** [comment]
Link seems incorrect. Do you mean this: https://angular.io/guide/router#configuration
