### ISSUE TITLE
Follow Angular style guide for Core and Shared modules

### ISSUE THREAD

**Issue by sjimenez77** [devonfw/my-thai-star#186]
Category: **enhancement**

Severity: **High**

**Description of issue / expected enhacement /Comments**
We must follow the Angular style guide about modules and project structure https://angular.io/guide/styleguide#application-structure-and-ngmodules when importing and using third party modules like the Covalent and Material ones and remove them from `core.module.ts`. 

Only the used Material and Covalent modules must be imported in the different application modules, so the `core.module.ts` will only be used to include application features and will be only imported in the main `app.module.ts`.

**Comment by akanagar** [comment]
Implemented the changes. Added material imports to respective modules and removed from core.module.ts.

**Comment by isandesh1986** [comment]
Not relevant after latest DA meeting. Hence removed from core team backlog.
