### ISSUE TITLE
Java - Specific sql files are not working for postgres

### ISSUE THREAD

**Issue by dario-rodriguez** [devonfw/my-thai-star#188]
Category: Bug

Severity: Medium

Expected behaviour:
When you execute the sql sencentes inside the file db/specific/postgresql/V0001__R001_Create_schema.sql it should ends successfuly

Actual/current behaviour:
When you execute the sql sencentes inside the file db/specific/postgresql/V0001__R001_Create_schema.sql it returns lot of erros.

Examples:
- In postgres Table is a reserved word, so you can't use it as table nable.
- In postgres User is a reserved word, so you can't use it as table nable.
- In postgres do not exists the sentence AUTO_INCREMENT. You must set the column as SERIAL.
- In postgres you can't use NO_CHECK in a constraint.
- In postgres do not exists the type BLOB.
and more...

Steps to reproduce (In case of bug)
Execute the sql java/mtsj/core/src/main/resources/db/specific/postgresql/V0001__R001_Create_schema.sql
in a postgres server.

Your environment:
Postgres server 9.6.1 (docker version)

**Comment by LillYttrium** [comment]
Issue is obsolete due to the decision that all DBs except for h2 and SAP Hana are being removed from my-thai-star Java. 
For further information see Issue #332.
