### ISSUE TITLE
DockerCompose - Docker build fails

### ISSUE THREAD

**Issue by bommox** [devonfw/my-thai-star#199]
It fails on docker-compose up.
```

$ ng build --configuration=docker
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by markusschuh** [comment]
Your build box has run out of memory. This build meanwhile seem to need more than 2GB memory - which is e.g. the default memory, a docker VM might have been set to during initial creation.

**Comment by baumeister25** [comment]
Clsoing this issue, as it seems to be solved
