### ISSUE TITLE
Password of gmail account stored in cleartext

### ISSUE THREAD

**Issue by thoptr-cap** [devonfw/my-thai-star#204]
Password of a Google mail account is stored in cleartext in several places.

For example: https://github.com/devonfw/my-thai-star/blob/develop/java/mtsj/core/src/main/resources/application.properties

Incomplete list: https://github.com/devonfw/my-thai-star/search?q=mythaistarrestaurant2501&unscoped_q=mythaistarrestaurant2501

Resolution hint "devon4j password guide": https://github.com/devonfw/devon4j/wiki/guide-configuration#password-encryption

**Comment by markusschuh** [comment]
A sample application as MTS need a good balance between readability and best practice security. The needed level of "secret management" depends on the requirements of the related context, which is inside of the responsibility of the resulting instance.

If the maven based password encryption were implemented inside the sample code, that lowers readability. Also there are other ways of "security management" which may need to be described in the future. I suggest, to keep the details out of the sample code.

For the sample I would keep some clear **dummy** values inside - e.g.  `dummypassword_needs_better_protection` - and refer also to a dummy server like `smtp.example.net`. Also inside a comment it should be noted, that this kind of implementation does not protect secrets and better methods should be used during implementation - potentially referring to the devon4j password guide.

Such developers can still run simple demos when getting familiar with the framework - but the security implication of using cleartext passwords is clearly visible.

Just removing the existing properties has no potential for such security guiding.
