### ISSUE TITLE
Generation of typescript classes for CTOs/CTS

### ISSUE THREAD

**Issue by tlueecke** [devonfw/my-thai-star#21]
My understanding was that we intended to generate the class definitions for the transport structures via CobiGen or at least if that is not possible, replicate them manually. Now we have own definitions with differing names and small structural changes which makes it difficult to understand.

_Example_:
```
export class BookingInfo {
    booking: ReservationInfo;
    invitedGuests?: [{email: string}];
}

export class ReservationInfo {
    bookingDate: string;
    name: string;
    email: string;
    bookingType: number;
    assistants?: number;
}
```
vs.
```
public class BookingCto extends AbstractCto {

  private static final long serialVersionUID = 1L;

  private BookingEto booking;

  private TableEto table;

  private List<InvitedGuestEto> invitedGuests;

  private OrderEto order;

  private List<OrderEto> orders;

  private UserEto user;
  [...]
}
```

**Comment by maybeec** [comment]
Protocol:

* consistent structure and naming on server and client representing the contract.
* there might be a wrapper on the client side to transform the data structures from the contract to whatever is needed or more appropriately on the UI

**Comment by maybeec** [comment]
Protocol 24.08. (architects meeting):

My-thai-star should describe the reference implementation in future. Therefore, we should provide examples for both worlds --- contract-first development as well as server data model first.
The decision is to reuse the data model from the server to be generated into typescript data model. This can be directly used for CRUD dialogs.
To show contract-first development, we should go for at least two use cases on the client UI, which need different data model to best handle data for the UI. This data has to be transformed in intermediate layer/service from the server etos to UI tos and vice versa.
