### ISSUE TITLE
Rest API not in api module

### ISSUE THREAD

**Issue by hohwille** [devonfw/my-thai-star#236]
Category: enhancement

Severity: Medium

Expected behaviour
MTSJ follows devon4j guidelines and structure so REST API (interfaces) are located in `api`

Actual/current behaviour (In case of bug)
REST API (interfaces) are located in `core`

Steps to reproduce (In case of bug)
:)

Description of issue / expected enhacement /Comments
move the interfaces to api and close this issue.

Your environment - windows/Linux, Devonfw version , component
not relevant.

**Comment by hohwille** [comment]
@lmarniazman changes are looking good. Will we receive a pull-request from it?
Also I found there is a REST service that does not have an interface at all:
https://github.com/devonfw/my-thai-star/blob/develop/java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/rest/SecurityRestServiceImpl.java

**Comment by lmarniazman** [comment]
@hohwille Should I create an interface for the service you mentioned and add it to the PR? I had the impression that the interface is missing on purpose as it may not be needed.

**Comment by hohwille** [comment]
> Should I create an interface for the service you mentioned and add it to the PR? I had the impression that the interface is missing on purpose as it may not be needed.

I already merged your PR. But I can see no purpose why this rest service should not be part of the API. Otherwise it can not be used  service client (via https://github.com/devonfw/devon4j/blob/develop/documentation/guide-service-client.asciidoc#service-client).
So if you can provide another PR resolving this, it would be awesome as we can then close this issue.
