### ISSUE TITLE
Add an scenario to upload a file.

### ISSUE THREAD

**Issue by jconcavi** [devonfw/my-thai-star#24]
As part of a project in Angular and JAVA we are facing some difficulties to upload a file from the Angular side to JAVA.

Maybe an example in this projects could help other developers to see how it's done.

**Comment by maybeec** [comment]
relates to #8

**Comment by sjimenez77** [comment]
From #8:

> oasp4j already provides a binary management. You might want to adapt it to also include a name of the binary. However, it specifies how to store binaries in the database correctly with blobs.
The imagemanagement does the same and therefore redundant, but in an incorrect way. It does store images as strings, which is not efficient and should not be a reference solution.
