### ISSUE TITLE
Duplicate interfaces in mtsj (usermanagement)

### ISSUE THREAD

**Issue by vapadwal** [devonfw/my-thai-star#247]
There are duplicate interfaces used in mtsj
com.devonfw.application.mtsj.general.common.api.Usermanagement
com.devonfw.application.mtsj.usermanagement.logic.api.Usermanagement

For details please refer to review comments in  PR https://github.com/devonfw/my-thai-star/pull/221

**Comment by Rohit90700** [comment]
This issue is solved and covered in PR https://github.com/devonfw/my-thai-star/pull/273

**Comment by vapadwal** [comment]
Closing the issue as it is fix in PR#273
