### ISSUE TITLE
[question] can I auto generate classes under api module

### ISSUE THREAD

**Issue by eonezhang** [devonfw/my-thai-star#267]
I want to confirm that, is there any tools to generate `Order.java`,`OrderLine.java`,`OrderedDishes.java` and classes under `to` package, such as `OrderCto.java`,`OrderEto.java`,`OrderSearchCriteriaTo.java` in our daily development.
```
├── ordermanagement
│   ├── common
│   │   └── api
│   │       ├── Order.java
│   │       ├── OrderLine.java
│   │       ├── OrderedDishes.java
│   │       └── to
│   │           ├── OrderCto.java
│   │           ├── OrderEto.java
│   │           ├── OrderLineCto.java
│   │           ├── OrderLineEto.java
│   │           ├── OrderLineSearchCriteriaTo.java
│   │           ├── OrderSearchCriteriaTo.java
│   │           ├── OrderedDishesCto.java
│   │           ├── OrderedDishesEto.java
│   │           └── OrderedDishesSearchCriteriaTo.java
```

**Comment by hohwille** [comment]
Please avoid asking questions as github issues.
However, the answert to your question is:
Yes, you can generate all the stuff with CobiGen:
https://github.com/devonfw/tools-cobigen
It already ships with templates fror devon4j, etc.
