### ISSUE TITLE
SAP Hana documentation

### ISSUE THREAD

**Issue by hohwille** [devonfw/my-thai-star#270]
With PR #205 we have integrated a SAP Hana showcase into MTS.
There was some offline word documentation passed how to setup this.
It seems as if this topic was not further proceeded after the merge.

With this issue I am requesting that we add the documentation to our official space:
https://github.com/devonfw/my-thai-star/tree/develop/documentation

It should be a new AsciiDoc file specific for SAP that is also linked from other places so it can be found easily (IMHO not only from MTS, but also from here: https://github.com/devonfw/devon4j/blob/develop/documentation/guide-hana.asciidoc).

The documentation that has been created as Word file and passed via email should already be most of the new content if converted to AsciiDoc. However, if I am not mistaken, I sent some mail after following this documentation with some issues I was facing that should result in improving the documentation content.

**Comment by vapadwal** [comment]
please see https://github.com/devonfw/my-thai-star/blob/develop/documentation/java-design.asciidoc#sap-hana

**Comment by vapadwal** [comment]
The PR is merge #271 so closing the issue
