### ISSUE TITLE
Cannot login as chief or cook

### ISSUE THREAD

**Issue by maybeec** [devonfw/my-thai-star#275]
If you login to the system as chief or cook, you get the notification, that authentication was successful, but afterwards, the app is broken and you cannot do anything further until you reload the website.

**Comment by Rohit90700** [comment]
In MTS user behavior(Access control of particular area) is define for every user role Like - 
Manager having rights to access prediction(SAP) 
Waiter having rights of Orders (Waiter cockpit)
but other user like Cook ,Barkeeper ,Chief does not have any usecase currently. So when it done using these logins it just behaves as said above.

**Comment by maybeec** [comment]
ok, but that's not true!? if you login as someone else, you will break the UI.
Therefore, I posted this bug. :/

**Comment by Rohit90700** [comment]
Yes , These user  Cook ,Barkeeper and Chief are defined in database side( i don't know why if not useful) then we can login it successfully but UI side these users are not available then UI will be break after the login.

**Comment by vapadwal** [comment]
I think we need a usecase for cook/chief/Barkeeper or we should remove them from backend

**Comment by maybeec** [comment]
if there is no use case, remove them. But I am quite afraid, about the behavior at all.
@sjimenez77 please can you do a review on the code level? There should be nothing at all, which breaks on the UI, if there is an "unknown user" to the UI, which is registered on the backend side.
What about new registrations? For me this completely sounds like an invalid implementation.

**Comment by sjimenez77** [comment]
Hi @vapadwal, let's get rid of them as there is no use case coming in the following months that makes use of those roles/credentials.

Please ask @suprishi to check the UI behaviour when login with wrong credentials in any case.

Thanks!

**Comment by vapadwal** [comment]
I think adding a message is good idea

**Comment by Rohit90700** [comment]
This issue is fixed and created PR https://github.com/devonfw/my-thai-star/pull/277 is merged ,hence we can close this issue.
