### ISSUE TITLE
Document available logins on login screen

### ISSUE THREAD

**Issue by maybeec** [devonfw/my-thai-star#276]
We should document the available logins on the login screen of my-thai-star to allow users to investigate the software and all its features without having to ask for the login data.

**Comment by sujith-mn** [comment]
Here are 3 different users on MTS
user0/password
waiter/waiter
manager/manager

**Comment by suprishi** [comment]
![image.png](https://images.zenhubusercontent.com/5d848bbb25cb270001668be2/ce900512-cca4-44f0-baeb-22bf248170a8)
![image.png](https://images.zenhubusercontent.com/5d848bbb25cb270001668be2/77d00d20-cf53-45d1-8f10-76133aba6243)

Implemented a clickable text in the login dialog which toggles a table showing all the credentials available for demo. Attached screenshot for reference.

**Comment by suprishi** [comment]
PR https://github.com/devonfw/my-thai-star/pull/1003

**Comment by suprishi** [comment]
PR merged after approval from Santos. Closing this issue.
