### ISSUE TITLE
Unable To Run MTS With SAP HANA Due To Two Factor Authentication Error.

### ISSUE THREAD

**Issue by Rohit90700** [devonfw/my-thai-star#278]
Missing/invalid field 'twoFactorStatus' for Table "User".
Note - In Two Factor Auth PR , 'twoFactorStatus' and 'secret' fields are not added in SAP HANA create table schema.

**Comment by hohwille** [comment]
@Rohit90700 Thanks for noticing and filing an issue!
See PR #228 - I assume some SQL change was missed out (maybe not applied for all DB dialects).

**Comment by Rohit90700** [comment]
This is is fixed and covered under the PR https://github.com/devonfw/my-thai-star/pull/291 ,hence closing it
