### ISSUE TITLE
Add "/services/rest/register" as unsecured API call

### ISSUE THREAD

**Issue by markusschuh** [devonfw/my-thai-star#281]
Category: Bug

Severity: Medium

Expected behaviour:
A registration inside My-Thai-Star should work

Actual/current behaviour:
When I run the my-thai-star sample from the docker compose example (inside Docker on Windows) the call from frontend to backend during registration always seems to return a 403 from the backend:
```
POST /api/services/rest/register HTTP/1.1
. . .

HTTP/1.1 403 Forbidden
. . .
```

Steps to reproduce:
Start fresh MTS via `docker-compose -f docker.compose.traefik.yml up -d`, access the MTS on IP of docker-machine "default" VM and port 8081. (works).
Now register and monitor the traffic to backend via Web developer tools (F12) in browser.

Description of issue / expected enhacement /Comments:
During registration the current user is not logged in. So I'd expect the API call to register would be another "unsecuredResources" - configured within `java/mtsj/core/src/main/java/com/devonfw/application/mtsj/general/service/impl/config/BaseWebSecurityConfig.java` - as it is also the case for e.g. `/rest/service/login` 
But currently it is not, so I guess the "403" is due to this. Or do I miss something here?

Your environment - windows/Linux, Devonfw version , component:
Windows 7, Docker Desktop (19.03), My-Thai-Star `develop` branch as of today.

**Comment by markusschuh** [comment]
I've opened this issue under the assumption, that some "register" functionality inside the devon4j backend of My-Thai-Star had already been realised. I thought, I have seen it already in some former example installation. 
But after some more code inspection, I more and more get the impression, that the "register" functionality may not have been realised inside the "mtsj" backend.
If it turns out, this assumption is true, this enhancement request may be closed, since it were far too specific then.

**Comment by methanome** [comment]
Hello,
We are facing a similar issue, the register is returning 403 and can't use the login either, have you figured out a way to add a new user or to prevent the 403 error? Thank you.

**Comment by markusschuh** [comment]
No, I did not.

I had only evaluated the java backend of the MTS demo application - and I can't detect, that "register" were already realized there. There is a "register" feature implemented in the node backend, though. But I have not yet tried this other backend.

**Comment by ssarmokadam** [comment]
We do not see any register functionality in devon4j backend. So it can be taken up as new enhancement. Issue already exists https://github.com/devonfw/my-thai-star/issues/343
