### ISSUE TITLE
Encryption/Decryption of JWT token

### ISSUE THREAD

**Issue by vapadwal** [devonfw/my-thai-star#286]
Currently the jwt token is not encrypted and can be easily decoded online https://jwt.io/

**Comment by markusschuh** [comment]
Is there anything of confidential character within the JWT, issued by the backend, that would require encryption? I personally can't identify a need for JWE here:
```
{
  "sub": "waiter",
  "scope": [
    "ROLE_Waiter",
    "mts.FindBooking",
    "mts.FindOrder"
  ],
  "roles": [
    "ROLE_Waiter",
    "mts.FindBooking",
    "mts.FindOrder"
  ],
  "iss": "MyThaiStarApp",
  "exp": 1569938822,
  "iat": 1569935222
}
```

**Comment by vapadwal** [comment]
Hi @sjimenez77 can you please put your few cents here

**Comment by sjimenez77** [comment]
Hi everyone,

In this case we are not sharing sensitive information so it would not be necessary, but if we consider MTS as a **reference** for devonfw we should be able to deliver this level of security.

See the following references:

- https://tools.ietf.org/html/rfc7519#section-12 
- https://tools.ietf.org/html/rfc7515#section-10.12

Anyway we could consider a combination of CSRF and JWT as another solution. Please, take a look at https://stormpath.com/blog/csrf-protection-jwt-spring-security for an example. Another good article could be https://x-team.com/blog/my-experience-with-json-web-tokens/

What do you think?

**Comment by isandesh1986** [comment]
Not relevant after latest DA meeting. Hence, closed.
