### ISSUE TITLE
angular config for urlpath to REST-API uses default value instead of external config.

### ISSUE THREAD

**Issue by markusschuh** [devonfw/my-thai-star#295]
### Expected behavior

As a newbie developer, I want to have a working example configuration so that quick review of the used techniques is possible.

### Actual behavior

At least the deployment via docker-compose currently seems to use the wrong restPathRoot / restServiceRoot, leading into failing calls to REST from client.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. clone the current "develop" branch
1. Modify the port "8081" within the docker-compose.yml to some different value. (Or do other changes, that ensure, the "http://localhost:8081/mythaistar" from client isn't the right url for REST calls."
1. run "docker-compose up -d"
1. Access the base URL. My Thai Star Homepage is displayed. The version string (bottom left) displays "docker version".
1. Access e.g. the menu. Monitor the network connections (browser's developer tools, network tab) Access to REST is always launched towards http://localhost:8081/mythaistar/services/rest/ - independent to the base URL of the frontend.

### Comments/Hints:

I am somehow aware of the logic, which is used to switch on "loadExternalConfig" for docker deployment, which overwrites some default variables with the modified config out of docker-external-config.json, which is provided via "/config" URL. The display of "docker-version" on the homepage is an indication, that this logic works correctly. Otherwise the  `this.version = configService.getValues().version` would not result in "docker-version".

But the same logic seems to fail now (**it has worked in the past**) for at least some cases, where the value of `restServiceRoot` is needed. The original value from `src/app/core/config/config.ts` is used instead of the overwrite, which exists inside the external configuration.

I have double checked, this now failing (worked before) behavior isn't caused on my side. I don't think, so. But another developer need to verify, if my recipe above runs into the same error. 

Also, I have tried to debug angular in order to localize the root cause, but failed to identify it, so far.
My best guess for the moment is, that issue may have been introduced by the upgrade to Angular 8? At least, my last more intensive checks for the communication to the rest API in MTS had been executed before that change.

### Affected version:

* OS: Windows/Linux/Mac? Tried on both Windows and Linux
* Browser: Chrome/Firefox/Safari? Tried with two different scenarios / base URLs

**Comment by markusschuh** [comment]
I did some more debugging. For that I've changed temporarily the following content:

- `angular/src/environments/environment.ts`:  `loadExternalConfig:` **true**
- `angular/src/app/core/config/config.service.ts`:  ´.get('/external-config.json')` instead of the former `/config`
- `angular/src/external-config.json`:  same content as in `docker-external-config.json`

Now after an  `ng serve` I was able to debug the "external config" mechanism on `http://localhost:4200` by setting breakpoints at

- XHR breakpoint for `ANY /external-config.json`
- in `src/app/core/config/config.service.ts` line 39  - the `return` in the `getValues()` 
- in `src/app/menu/services/menu.service.ts` line 30 - when `this.restServiceRoot` is read from configService
- in the same file, in line 71 - when `this.restServiceRoot` is used, to create the rest call

On first try, I have just continued after break until I have clicked on "Menu" inside the "My Thai Star" top line. This reached the last breakpoint mentioned above (immediately before the REST call). And the following two watched expression showed the issue:

```
this.configService.getValues().restServiceRoot: "api/services/rest/"
this.restServiceRoot: "http://localhost:8081/mythaistar/services/rest/"
```

The expected (and needed) result were, that both those expression had the value `"api/services/rest/"`

After another debug run I have the impression, the root cause of the issue is the wrong order of the `constructor` and the `call to get external config`. The `call to get external config` should come first - but currently the constructor is called first and such sets the internal values. Even when the call for external config is executed correctly later, the variables of the already instantiated service object does not get the now updated configuration.

This issue - and potential solutions - are discussed e.g. [here](https://stackoverflow.com/questions/49163532/angular-v5-service-is-getting-constructed-before-app-initializer-promise-resol).

**Comment by markusschuh** [comment]
I have again tried to narrow down the root cause, but progress is slow and still incomplete:

1.  Solutions from the link mentioned in my last comment seem not to be that helpful, since basically they suggest to introduce a Promise - but this is already the case anyway.
1.  I have checked out some different commits from mts to identify the commit, that had introduced this issue. which resulted in https://github.com/devonfw/my-thai-star/commit/fb0f985a9c16e1519b7f2a295d693df8ccfe8ac0 as first commit, where issue has appearde. So the upgrade of ngrx from 7.4.0 to 8.3.0 was the trigger.
1. I have checked the ngrx [CHANGELOG](https://github.com/ngrx/platform/blob/master/CHANGELOG.md) - but I can't find anything related to this issue.
1. I see some discussion on github/ngrx with respect to [APP_INITIALIZER](https://github.com/ngrx/platform/issues?utf8=%E2%9C%93&q=APP_INITIALIZER). ngrx seem to be initialized before APP_INITIALIZER.
1. A ngrx-8.4.0 has been published - but I can't see changes inside the Changelog, which were related to APP_INITIALIZER

Every topic in this list is still quite vague - but maybe those collected hints help somebody else to resolve this issue.

**Comment by markusschuh** [comment]
ngrx/platform#931 describes the issue in detail. Proposed workarounds - as far as I understand:

**Alternative A**:  do not use ConfigService within constructor.
With respect to only `restServiceRoot` and `restPathRoot`m this would need changes within:
```
src\app\book-table\services\book-table.service.ts
src\app\cockpit-area\services\clustering.service.ts
src\app\cockpit-area\services\prediction.service.ts
src\app\cockpit-area\services\waiter-cockpit.service.ts
src\app\email-confirmations\services\email-confirmations.service.ts
src\app\menu\services\menu.service.ts
src\app\sidenav\services\sidenav.service.ts
src\app\user-area\services\user-area.service.ts
src\app\user-area\store\effects\auth.effects.ts
```

**Alternative B**: introduce `provideBootstrapEffects` as in the provided [demo](https://github.com/brandonroberts/effects-issue-example/commit/6d648b04b568d39e864b93146fe684daa06240d1)
This will need fixes inside
```
src\app\app.module.ts
src\app\home\container\home\home.component.spec.ts
```
But based on the further discussion this workaround seems to have its limitations.

**Comment by markusschuh** [comment]
I have tested implementation of "Alternative B" as described above, but that couldn't solve the issue. Also updating ngrx to a newer version - now committed in #309 to develop branch anyway - could not solve this issue. Somehow I had expected this - but it was worth to check those not-too-difficult to implement changes.

I guess the above "Alternative A" is still a hot candidate for a workaround. I have not managed to test it yet.

**Comment by dario-rodriguez** [comment]
Hello @markusschuh , this issue is solved and merged into develop. Can you check if now everything is working fine?

If yes we can close this issue

**Comment by markusschuh** [comment]
Thx, the provided change fixes this issue.

Two more comments:

- I personally would try to keep unrelated text changes (e.g.  reformatting of code blocks) out of such fixes / within separate commits. This would make it easier for others to understand the fixes.
- I can see, that the fix removes the assignment of external_config variables within class constructors - so I was on the right track inside my analysis. ;-)
