### ISSUE TITLE
angular - external configuration doesn't work properly

### ISSUE THREAD

**Issue by dario-rodriguez** [devonfw/my-thai-star#296]
### Expected behavior

When you deploy the application user the docker-compose.yml, the angular application should take some configuraiton by calling the /config endpoint. It makes the call but it doesn't use the configuration loaded properly. The external configuration said that the endpoint is api/, but the application use localhost:8081/mythaistar/... (the default configuration)

### Actual behavior

The application do not use porperly the configuration loaded from the external source.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Deploy the application using docker. In the root folder of My Thai Star execute the command `docker-compose up -d`
2. Try to load the menu
3. Check the URL that the application is using in order to load the menu. The correct value should be /api/services/rest/...

### Affected version:

Last commit in develop branch.

* OS: Windows/Linux/Mac?
* Browser: Chrome/Firefox/Safari?

**Comment by markusschuh** [comment]
duplicate pf #295
