### ISSUE TITLE
No Communication between front- & back-end when using root docker-compose

### ISSUE THREAD

**Issue by Fasust** [devonfw/my-thai-star#310]
### Expected behavior
I am running My Thai Star locally using the docker-compose file in the root directory of the repository. It should run perfectly out of the box.

### Actual behavior
But when ever the front-end makes a http call to the back-end it gets the following two responses: 

- "504 Gateway Timeout (from ServiceWorker)" followed by
- "405 Not Allowed"

#### Traffic
![Browser](https://user-images.githubusercontent.com/30209993/68780513-b69d8a80-0636-11ea-9764-fb86d029f6d1.png)
### Steps to reproduce (bug) / Use Case of feature request (enhancement)

This happens for any communication between front-end and back-end: Search, Authentication, Booking.

### Affected version:
Current Master Branch

* OS: Windows
* Browser: Chrome

**Comment by sjimenez77** [comment]
Hi @Fasust, thanks for posting this issue.

After checking this with the team, they just told me that this is in fact the consequence of this other issue #295 we are now currently solving.

Please stay tuned for the solution!

**Comment by markusschuh** [comment]
I'd say this is a duplicate of #295 - but to ensure that, you should first check two details:

1. Check the full URL for "..../search" (Hoover over the red "search".) Does it start with "http://localhost:8081/mythaistar/"?  
1. Is the base URL - which you have entered inside browser to access the angular frontend of your docker composed My-Thai-Star a **different** one than this "http://localhost:8081/mythaistar/"

If you answer both questions with "yes", this is indeed a duplicate of #295 

At the moment, the only way I am aware to work around this recently new introduced issue is replace the values for restPathRoot and restServiceRoot within `angular/src/app/core/config/config.ts` with the needed value, which are inside `angular/docker-external-config.json`. Afterwards rebuild and restart the angular docker-compose service.
That replaces the automatic replacement - which currently fails - with a manual procedure.

**Comment by Fasust** [comment]
Thanks for the quick reply 😊
Regarding your questions: 

1. Yes, it is: _http://localhost:8081/mythaistar/services/rest/dishmanagement/v1/dish/search_.
2. Yes, i used _http://localhost:8081/restaurant_ because _http://localhost:8081/mythaistar/_ is stuck on an infinite loading screen.

@markusschuh I just tried your fix and it works. Thank you very much 😁

**Comment by dario-rodriguez** [comment]
Hello @Fasust , this issue should be already solved. Can you check it? Then we can close this issue.

**Comment by Fasust** [comment]
@dario-rodriguez Yes, it does work now :) 
Thank you.
