### ISSUE TITLE
Question/Discussion: Reason for "Book a Table" & "Invite Friends" -Tab on "Book Table"-Page

### ISSUE THREAD

**Issue by Fasust** [devonfw/my-thai-star#313]
**Category: Question**

Hey,
I have a question regarding the Angular Front-end. More specifically, the _"Book Table"-Page_.
If I understand the documentation correctly, a booking can have any number of guests. These guest should receive an email when they are invited to a booking.

The Angular front-end has 2 tabs on the _"Book Table"-Page_, one for making a booking and one for inviting a friend. Why does the _"Invite a friend"_-tab create a whole new booking? could it not just be a place where I can can send invites to the booking I created in the _"Book a Table"_-tab?

![Book a Table](https://user-images.githubusercontent.com/30209993/69331908-de53aa80-0c55-11ea-8224-69d2fba9b997.png)
![Invite a friend](https://user-images.githubusercontent.com/30209993/69331947-f5929800-0c55-11ea-9e65-60d22c9c4c3b.png)

**Comment by sjimenez77** [comment]
Hi @Fasust,

These are two different use cases:

1. **Book a table:** In this case the user does not specify the guests, only the number and there is no notification.
2. **Invite friends:** In this other case the user adds the guests email addresses that would receive a notification to confirm the invite. The emais are validated. 

It is important to take into account that only the devon4node implementation simulates these email sending. In other cases you need to check the backend console to see the simulated content of the email notifications. If you have access to the Capgemini netowrk try this:

- My Thai Star devon4node at http://de-mucdevondepl01:8091/
- Mail dev server at http://de-mucdevondepl01:8092/

Best regards,
Santos

**Comment by Fasust** [comment]
@sjimenez77,

Okay, Thank you very much for the explanation. 
So in the second use case it is currently only possible to invite one friend / have a table for 2 people, correct?
