### ISSUE TITLE
"docker-compose up" does not run successfully

### ISSUE THREAD

**Issue by chnicu** [devonfw/my-thai-star#323]
Category: Bug

Severity: Medium

Expected behaviour (In case of bug)
Docker build runs, builds everything, docker container run and are accessible

Actual/current behaviour (In case of bug)
On a fresh and previously unused docker installation (on Windows): Build fails when building angular Dockerfile on line 4:

`RUN npm i -g yarn`

This step can be brutally overcome by changing this line to 
`RUN npm i -g yarn --force`
(I doubt it is good, but I tried it and built then continued ;-) )

But then it fails later with:
```
Step 8/16 : RUN yarn build --configuration=docker
 ---> Running in 1eca8a6a1e7b
yarn run v1.21.1
$ ng build --configuration=docker
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

Steps to reproduce (In case of bug)
trigger `docker-compose up` and wait. (At least on a fresh Docker installation)

Description of issue / expected enhacement /Comments

Your environment - Windows Server 2019, Devonfw version ? , component my-thai-star, develop branch

**Comment by chnicu** [comment]
Just tried it: same issue with "master" branch

**Comment by chnicu** [comment]
Here is the detail about the first build error:
```
Step 4/14 : RUN npm i -g yarn
 ---> Running in 363a79f9ca81
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/yarn/bin/yarn.js
npm ERR! dest /usr/local/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/local/bin/yarn'
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-22T18_50_41_183Z-debug.log
ERROR: Service 'angular' failed to build: The command '/bin/sh -c npm i -g yarn' returned a non-zero code: 239
```

**Comment by dario-rodriguez** [comment]
Hello @chnicu , you are right. Since the node moved the LTS version to 12.X, yarn is already included in the docker image and you don't need to install it again.

The second error that you are suffering is related to your RAM. Can you share more details? I tested it few minutes ago in my labtop (WIN 10 16GB). Also I tested it in a CentOS 7.6 virtual machine with 4GB of RAM and it also works.

Anyway, I will create a PR removing the yarn installation step in order to solve the problem.

Thank you.

**Comment by chnicu** [comment]
Hi Dario,

Thank you for the quick reply.

I removed the line „RUN npm i -g yarn” from the Dockerfile and it does not come up with the yarn error any more. Thanks for that. 😊

However, I still have the “JavaScript heap out of memory”.

Here is what I (still) get:

[cid:image002.png@01D5D2E1.8AC09890]

It’s not an Memory issue of windiws. I’d rather say it’s within the container when it tries to execute “yarn build --configuration=docker”.

Anyhow, my (Windows) Machine would offer 12GB.

Best regards,
   Christian

**Comment by markusschuh** [comment]
Check the total memory that is available to all your containers with

`docker system info --format "{{ .MemTotal }}"`

To my experience this needs to be 4 GB as minimum for the MTS build. If also other containers are running during this build, you may even need more. Depending on the used docker technique on Windows this may need a recreation of the docker host VM with more than the default assigned memory.

See also the older, but may be a bit related #199

**Comment by chnicu** [comment]
Thank you, Markus. That did indeed the trick :-)
I had to allow more memory to the docker desktop.

**Comment by baumeister25** [comment]
Clooing this issue, as it seems to be solved
