### ISSUE TITLE
Removal of other DBs from MTSJ Java

### ISSUE THREAD

**Issue by vapadwal** [devonfw/my-thai-star#332]
As discussed previously we need to keep only h2 and SAP Hana DB for mtsj java backend

Currently h2/hana/mysql/oracle/postgresql/sqlserver are supported for mtsj java

As it is difficult to maintain all the databases. It was decided in architect meeting that we should only support any two databases.

As right now only we maintain h2 and Hana database. So we can decide to remove all the other DB scripts.

**Comment by ssarmokadam** [comment]
Other DB related scripts are already removed. Hence closing this issue.
