### ISSUE TITLE
Menu entries invisible after "user0" login

### ISSUE THREAD

**Issue by markusschuh** [devonfw/my-thai-star#354]
### Expected behavior

As a MTS user, I want use MTS even when logged in as "user0".

### Actual behavior

When MTS login is with default user credentials ("user0"/"password") the menu entries are no longer visible (except profile edit and language selector.)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. git clone https://github.com/devonfw/my-thai-star.git && cd my-thai-star && docker-compose up
2. Open browser and login as "user0" / "password"

### Comments/Hints:

The JavaScript console shows:

` ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
`

### Affected version:

* OS: Windows 10
* Browser: Firefox

**Comment by akanagar** [comment]
Implementation in progress..managed customer role for user0 from backend and frontend..

**Comment by akanagar** [comment]
Implemented the changes.
PR link: https://github.com/devonfw/my-thai-star/pull/992
