### ISSUE TITLE
Caching of CORS OPTIONS request

### ISSUE THREAD

**Issue by marpuch** [devonfw/my-thai-star#39]
Right now for every backend query the browser generates two requests. The first one is the OPTIONS requests which looks e.g. like this:

`OPTIONS http://de-mucdevondepl01:9090/mythaistar/services/rest/dishmanagement/v1/dish/search HTTP/1.1 (...)`

The response allows for the CORS request to be performed by setting the headers:

`Access-Control-Allow-Methods: OPTIONS,HEAD,GET,PUT,POST,DELETE,PATCH`
`Access-Control-Allow-Headers: content-type`
`Access-Control-Allow-Credentials: true`

The second request is the normal query request like e.g. the POST:

`POST http://de-mucdevondepl01:9090/mythaistar/services/rest/dishmanagement/v1/dish/search HTTP/1.1 (...)`

It would be nice to allow the caching of the first OPTIONS request on the browser just to generate less load on the server. I tested it a bit and it was enough to add the following CORS header in the reply to make it happen:

`Access-Control-Max-Age: 3628800`

**Comment by sjimenez77** [comment]
In a CORS scenario OPTIONS pre-flight requests are sent **by the browser** automatically to ensure that the following request is safe to be sent. As the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) describes:

> The Cross-Origin Resource Sharing standard works by adding new HTTP headers that allow servers to describe the set of origins that are permitted to read that information using a web browser.  Additionally, for HTTP request methods that can cause side-effects on server's data (in particular, for HTTP methods other than GET, or for POST usage with certain MIME types), **the specification mandates that browsers "preflight" the request**, soliciting supported methods from the server with an HTTP OPTIONS request method, and then, upon "approval" from the server, sending the actual request with the actual HTTP request method. Servers can also notify clients whether "credentials" (including Cookies and HTTP Authentication data) should be sent with requests.

In our case, an Angular SPA, as we send/receive JSON data to a server with CORS enabled the requests must be "pre-flighted". In other scenarios, The only allowed values for the Content-Type header that could not be "pre-flighted" are:

- application/x-www-form-urlencoded
- multipart/form-data
- text/plain

**Comment by marpuch** [comment]
But my point is, we do not need to preflight every server call. Let's say we want to call `/mythaistar/services/rest/dishmanagement/v1/dish/search` 10 times. It's ok, if the browser asks for permission using the OPTIONS header once. Only the first call is needed. Then we can cache the response for a defined time frame. This is what the `Access-Control-Max-Age` response header is for. What do you think?

**Comment by sjimenez77** [comment]
Ok. Let's try it. Thanks for the suggestion. I will come back with the results.

**Comment by ssarmokadam** [comment]
I have done this changes and raised PR#93

**Comment by sjimenez77** [comment]
Issue closed due to solution provided #93 and inactivity.
