### ISSUE TITLE
Incomplete authorization

### ISSUE THREAD

**Issue by maybeec** [devonfw/my-thai-star#4]
Currently, there is just one `@RollesAllowed` annotation for authorization purposes in the `BookingmanagementImpl` class. Authorization should be done for every method.
Please also check other component facades.

**Comment by maybeec** [comment]
Protocol 26.07.

* Introduce an anonymous role to not break static analysis and make open access more explicit
* Might be discussed as well in the architects meeting to be inserted into the oasp4j documentation

**Comment by sjimenez77** [comment]
Issue closed due to provided solution and inactivity.
