### ISSUE TITLE
Huge size of the /dish/search response

### ISSUE THREAD

**Issue by marpuch** [devonfw/my-thai-star#40]
Right now the /dish/search queries respond with a huge size JSON containing the BASE64 encoded content of some image files making the response body ~500kB big. There are some issues with this approach:

- It scales poorly. The list contains now 8 dishes and the payload is already this big.
- The images can not be cached by the browser. Every new request means the images must be reloaded as well.
- It kills my proxy when I try to play with the application. ;)

I think the proper way would be rather to put the images into the client side of the application and to pass just the links to it. I know - this introduces some tight coupling between the client and the backend. I think this might be inevitable.

Other idea - hold the images on the backend, but make them accessible normally, not as part of the JSON object. Then you will be able to turn on the caching again only for those.

**Comment by sjimenez77** [comment]
For the moment it was only a workaround as currently we do not have an administration cockpit to create new dishes with an image upload **yet**. 

We already know that it is not the ideal scenario and when we improve the administration panel this image management will be completely removed to a usual upload scenario. 

Maybe we could request the whole thing as an enhancement. What do you think?

**Comment by marpuch** [comment]
Thanks for the kind reply. Sure thing. It is an enhancement.
