### ISSUE TITLE
MTS for Quarkus 

### ISSUE THREAD

**Issue by ssarmokadam** [devonfw/my-thai-star#424]
As a user, I want to create my-thai-star with Quarkus. we will break down my-thai-star into different services and will do some refactoring in it.

More details for refactoring:
- In MTS refactoring we will have single module project and not multi-module
- Services will be seperate microservices (already done by tkit people)
- Current implementation have BFF pattern we do not need it we will use gateways from ingres or Istio
- Current implementation have DTO we will use ETO/CTO like devon4j
- we will still follow api and impl structure but will avoid other unnecessary interfaces or abstract classes
- We will not return Response object from REST we will return ETO/CTO objects
- We will use authentication in ingres or our own impl as spring security will not work with quarkus
- Inter service communication might be done using microprofile(need to verify it once again)
- To integrate an email service we will use docker container with email

**Comment by ssarmokadam** [comment]
Current status: Merged 2 basic services in branch https://github.com/devonfw/my-thai-star/tree/quarkus-ms Student is working on one service. Team core can take rest of the services.

**Comment by ssarmokadam** [comment]
We will start with one service ordermanagement/bookingmanagement in next sprint

**Comment by ssarmokadam** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-62825383d986530011ae300d/issues/devonfw/my-thai-star/424?planning-poker) with ZenHub @isandesh1986 @sujith-mn

**Comment by isandesh1986** [comment]
Not relevant after latest DA meeting. Hence, removed from core team backlog
