### ISSUE TITLE
Information disclousure, password plaintext storage

### ISSUE THREAD

**Issue by opermajki** [devonfw/my-thai-star#55]
On request below application returns sensitive user information like password. 
It means also that passwords of users are stored in databese in plain text. It should be stored only as a hash of user password.

References: 
https://www.owasp.org/index.php/Information_Leak_(information_disclosure)
https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet

Request:
```
POST /mythaistar/services/rest/bookingmanagement/v1/booking/search HTTP/1.1
Host: xxxx
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3YWl0ZXIiLCJzY29wZSI6W3siYXV0aG9yaXR5IjoiUk9MRV9XYWl0ZXIifV0sImlzcyI6Ik15VGhhaVN0YXJBcHAiLCJleHAiOjE1MTA4MzczNzksImlhdCI6MTUxMDgzMzc3OX0.gjZsyVCmuCuxVr9dEDDyr9mXJ_yC04yx3dOG03dR76zvoEVBZTqZa5FlRKQ3s_USGfuaNL0CW0OiRu5cceYu1A
Content-Type: application/json
Referer: xxxx/reservations
Content-Length: 87
Origin: xxxxx
Connection: close
{"email":null,"bookingToken":null,"pagination":{"size":8,"page":1,"total":1},"sort":[]}
```
Response:
```
HTTP/1.1 200 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Access-Control-Allow-Origin: xxxx
Vary: Origin
Access-Control-Allow-Credentials: true
X-Application-Context: xxxx
Date: Thu, 16 Nov 2017 12:20:23 GMT
Content-Type: application/json
Connection: close
Content-Length: 7300

{"pagination":{"size":8,"page":1,"total":36},"result":[{"booking":{"id":0,"modificationCounter":1,"revision":null,"name":"user0","bookingToken":"CB_20170509_123502555Z","comment":"Booking Type CSR","bookingDate":1510590903057,"expirationDate":1510587303057,"creationDate":1510158903057,"email":"user0@mail.com","canceled":false,"bookingType":"COMMON","tableId":0,"orderId":0,"assistants":3,"userId":0},"table":{"id":0,"modificationCounter":1,"revision":null,"seatsNumber":4},"invitedGuests":[],"order":{"id":0,"modificationCounter":1,"revision":null,"bookingId":0,"invitedGuestId":null,"bookingToken":null,"hostId":0},"orders":[{"id":0,"modificationCounter":1,"revision":null,"bookingId":0,"invitedGuestId":null,"bookingToken":null,"hostId":0}],"user":{"id":0,"modificationCounter":1,"revision":null,"username":"user0","password":"password","email":"user0@mail.com","userRoleId":0}},{"booking":{"id":1,"modificationCounter":1,"revision":null,"name":"user1","bookingToken":"CB_20170510_123502575Z","comment":"Booking Type
[...]
```

**Comment by hohwille** [comment]
@opermajki thanks for the finding and this issue.
The devonfw initiative is IMHO a very great initiative with lots of highlights but to be very honest, this issue on the other hand shows that there are also low-lights. It is a pitty that such an issue exists in devonfw that claims to reduce risks and be a great solution for IT security. If the detailed guides that we have online would have been read and honored, this security and data-privacy desaster would of course not have happened. The actual pain-story however is that we have not been able to make any progress and more or less ignored this issue for 1+ year!
I marked this sisue as bug and blocker and will put priority on this so we will get this fixed. Sorry, for this pain-story but shit happenes. Lets try to make the best for the future, keep on going to continuously improve devonfw and my-thai-star and make things like this become history to forget one fine day :)

**Comment by hohwille** [comment]
For the record. The result contains information about different users of the my-thai-star application like this:
```
"user": {
      "id":0,
      "modificationCounter":1,
      "revision":null,
      "username":"user0",
      "password":"password",
      "email":"user0@mail.com",
      "userRoleId":0
    }
```
We should never ever store and never never ever allow to retrieve passwords of users. This is completely inacceptable. If we would do so in an application for our customer even if there is no demand/requirement about this it would be a bug and we could easily get sued for such mistakes as IT security (at least for such obvious cases) is an implicit MUST requirement.

Also regarding GDPR (EU data privacy rights) we should be careful about personal data such as email addresses. It may be acceptable for an admin to retrieve a list of users with their email addresses, names, etc. but if regular users of the system (especially guests) may retrieve such personal data of other persons this is also a severe bug that could result in suing us and getting a expensive fine.
