### ISSUE TITLE
Hardcoded secrets

### ISSUE THREAD

**Issue by marpuch** [devonfw/my-thai-star#67]
In `TokenAuthenticationService` one can find `static final String SECRET = "ThisIsASecret";`. This is the most important secret the application handles right now as it is used to sign the JWT tokens. There are several problems I see with this implementation like:

- The entropy of `ThisIsASecret` is rather low.
- The token is hardcoded which prevents any changes without code recompilation.
- As it is hardcoded, the secret resides in the repository, so a successful attack on the repo means a successful attack on the application (raises the attack surface).
- If the application is successfully attacked (security breach), the dev team will be suspected of leaking the secret. -> We should rather make sure the dev team can deny having any knowledge about the secret on prod instances of the system.

I consider it dangerous to show such approach in a reference implementation. I would propose to do it following way:

1. Put the secret in a `secret.properties` file.
2. Include `secret.properties` in `.gitignore`
3. When the application is deployed and the `secret.properties` file is missing, it will be created. The secret will be generated using `SecureRandom` class, have the entropy of at least 128 bits and be encoded with base64.
4. The `secret.properties` file, generated by the application, will have same access rights as the application. Assuming the app is running in a separate user account, the secret will be protected from other non-admin users by the filesystem access rights.

This way we could address the issues above and show proper secret handling in the application. This would put no additional effort into how the application needs to be deployed.

PS. I know this case could be also handled by key stores, but I am no fan of them. The password to the key store would still need to be hardcoded in the application. And the deployment would be way harder.

**Comment by markusschuh** [comment]
I agree to all your statements - and there is need, to implement that finside MTS.
Based on "security management services" typical cloud environments offer today, I suggest the following slight extension to the your description:

The absolute path name of such a `secret.properties` file should be read from an _optional_  property defined inside `application.properties` - and fall back to the default of a `secret.properties` inside the application's root path.

Thus the application can still be provided as WAR. Configuration can be done by an external application.properties which is just put inside the same directory of this WAR file. And inside the application.properties path to externally provided secret files can be given, which help to keep compromise risk for such confidential secrets inside runtime environments low.

E.g. using Kubernetes [Secrets](https://kubernetes.io/docs/concepts/configuration/secret/) or similar services. And if those services are not available, the approach with a secret in a file, which is secured against unauthorized access as far as possible / as necessary is a good fall-back.

**Comment by markusschuh** [comment]
As a reference, how other frameworks handle the secret, I suggest https://www.playframework.com/documentation/2.7.x/ApplicationSecret

This can't be - and should not be - copied here, of course. Especially since it relies on SBT as build tool and uses HOCON as configuration syntax.

But I like their idea, to put a "changeme" as dummy value into the samples - and implement code, that stops the applications outside of development to use that secret and inside development with a clear and helpful warning.
Also there is a method `playGenerateSecret` implemented, which generates a fresh random secret. 

I assume, spring security may offer similar helpers - I just have not found the time to search that intensively for this inside spring framework.
