### ISSUE TITLE
Database toggle

### ISSUE THREAD

**Issue by hohwille** [devonfw/my-thai-star#70]
Currently we have a hard-coded dependency to h2 in our pom and out-commented dependencies for other DBs. 
https://github.com/oasp/my-thai-star/blob/develop/java/mtsj/core/pom.xml#L274

This is not the professional way to do it.
Instead we should create maven profiles for each DB and make h2 active by default. Further each maven DB profile can also trigger a variable that will be used via filtering so the proper spring config for the chosen DB is also selected. Then all you need to do is start maven build with `-Ppostgresql`, `-Pmariadb`, `-Poracle`, ... and that is all.

**Comment by hohwille** [comment]
Cool. With my solution we can also do:
```
mvn install -Poracle -Dmts.database.version=12.1.0.3
```
Seems to be a lot more flexible now.
We can now also really test the configs what is not possible with an XML comment.
We could have a CI (e.g. Jenkis) setup that tests the build for all available databases if we wanted to. Of course on that build-server all that databases would need to be installed (or whereever else) and configured (jdbc URL, login, password). However, just a nice to have...

**Comment by hohwille** [comment]
Should we also allow to change DB for (JUnit) tests?
IMHO helpful but I would not recommend that `-Ppostgresql` would automatically trigger postgresql to be used for tests as I might not have postgresql available on my build machine but want to build a release for postgresql anyhow.
My suggestion therefore would be:
* create also `mts.test.database.*` properties for test-DB dependency and configs.
* add another profile "testdb" to trigger that test-properties are set equal to run-properties so `-Ppostgresql,testdb` would change to postgresql and also run the JUnits on top of postgresql.

WDYT?

**Comment by amarinso** [comment]
One thing that may be uncomfortable in a concrete project is being "forced" to use a profile to do the compilation... So, if you are going to use Oracle for the whole life of the project, having to write -Poracle is not only boring but maybe error prone...

Maybe it's only a matter of documenting that for a project you should set your ddbb profile as "default", 

Can we set h2 as another profile but mark it as <activeByDefault> in maven?

**Comment by jconcavi** [comment]
I agree with Angel, usually the projects are not going to use H2 by default, we need to have a mechanism to choose a default value to avoid the -Ppostgres for all the compilations, and only in some specific cases use the profile flag.

**Comment by hohwille** [comment]
Sorry to be pragmatic, but you were occupying an existing ticket. The problem of this issue is resolved and therefore I will close it.
Also I do not see your problems. You can activate profiles for a devon project in `conf/.m2/settings.xml` so you do not have to provide the profile on each maven call. Also there is a default.
If you have something concrete to improve then file a new issue.
