### ISSUE TITLE
Start tagging working states

### ISSUE THREAD

**Issue by maybeec** [devonfw/my-thai-star#97]
I just first tried mts to adapt an upcoming for it. However, I was not able to as the current version does not run properly and there is no recent release tag, which provides a working deployment state.
Please start to have a proper release management.

**Comment by hohwille** [comment]
At least we introduce CI that should help us with quality and reduce build breaks (e.g. when merging PRs):
https://github.com/oasp/my-thai-star/pull/99

**Comment by sjimenez77** [comment]
AFAIK this issue could be closed, right?

**Comment by hohwille** [comment]
IMHO this could be considered as a duplicate of #123 and therefore closed.
@maybeec If you do not respond we will close this soon.
