### ISSUE TITLE
Integrate register user from frontend to backend.

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/my-thai-star#980]
Backend integration can be found here #343

**Comment by suprishi** [comment]
Implemented user registration from front-end:
1. Added action, reducer and effects in the `auth` store for registration.
2. Added an extra field for `username` in the sign up form and passing the form data on submit.
3. Updated `register()` function in the `UserAreaService` to accept `usesrname` in addition to `password` and `email` as parameters.

Will create a PR after testing locally.

**Comment by suprishi** [comment]
PR link https://github.com/devonfw/my-thai-star/pull/994

Also corrected failing unit test cases.
