### ISSUE TITLE
Provide appropriate error message when trying to register an already registered user

### ISSUE THREAD

**Issue by suprishi** [devonfw/my-thai-star#993]
As an end-user, I want a proper error message when I try to register a user with existing credentials so that I can stop attempting to register with the same credentials.

Currently, a generic error message is given with the status code 500 stating: "An unexpected error has occurred! We apologize any inconvenience. Please try again later." A better message would be something along the lines of "User already exists".

**Comment by ghost** [comment]
PR #1029  Provided the appropriate message when duplicate user try to register.

**Comment by ghost** [comment]
PR #1032 Changed message from "Username already exists" to "Username is already taken".
